### ISSUE TITLE
ImportError: cannot import name 'Bonito' from 'bonito'

### ISSUE THREAD

**Issue by djlwzw** [BatsResearch/bonito#39]
"from bonito import Bonito"
I installed bonito library version 0.2, Python version 3.8, why does it show no Bonito

**Comment by nanyyyyyy** [comment]
Thank you for your interest in Bonito. Could you please provide more information?

**Comment by djlwzw** [comment]
Thank you for your reply, I tried to reinstall after running this command "! git clone https://github.com/BatsResearch/bonito.git ", problem solving, can now run the Bonito model. I now have another question, if I want to label an unlabeled dataset with a custom set of labels, can I do that with this model? I tried to select task_type=topic classification, but the classification results are given according to the AGNews category.

**Comment by nihalnayak** [comment]
It's great to hear that you resolved the issue! We did notice for tasks like topic classification, the model overfits to classes from the training datasets such as AGNews. There are a couple of workarounds for this issue: 
1. Modify the [process function](https://github.com/BatsResearch/bonito/blob/ddfe7077a36178e97a32523117cc3213dad06c23/bonito/abstract.py#L57C1-L65C1) to include the custom classes as instructions: 
```
        def process(example):
            input_text = "<|tasktype|>\n" + full_task_type.strip()
            input_text += (
                "\n<|context|>\n" + example[context_col].strip() + "\n<|task|>\n"
                "{{context}} classify the following into X, Y, or Z.\n<|pipe|>\n" # new instruction
            )
            return {
                "input": input_text,
            }
```
2. Use instruction-tuned model such as [BatsResearch/Mistral-7B-v0.1-P3](https://huggingface.co/BatsResearch/Mistral-7B-v0.1-P3) since you only want to classify a text into its categories. 

I hope this helps!

**Comment by djlwzw** [comment]
Thank you very much for your valuable advice! I really appreciate your time and effort to help me. Solved my current confusion. Thanks again!
